name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package index
            sudo apt-get update
            
            # Install Docker if not installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get install -y docker.io
            fi
            
            # Install Docker Compose if not installed
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            # Add user to docker group
            sudo usermod -aG docker $USER
            
            # Navigate to project directory (create if doesn't exist)
            mkdir -p /home/ubuntu/fastapi-book-project
            cd /home/ubuntu/fastapi-book-project
            
            # Pull latest changes
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/nyainda/fastapi-book-project.git .
            fi
            
            # Stop and remove existing containers
            docker-compose down
            
            # Build and start containers
            docker-compose up -d --build
            
            # Clean up unused images
            docker image prune -f

            # Check if containers are running
            docker ps