# .github/workflows/ci.yml
name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest


 name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python  # This is needed for installing dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker Image  # Build the image
        run: docker build -t my-fastapi-app .

      - name: Push Docker Image to Railway Registry # Push to Railway
        run: |
          docker login -u ${{ secrets.RAILWAY_DOCKER_USERNAME }} -p ${{ secrets.RAILWAY_DOCKER_PASSWORD }} registry.railway.app
          docker tag my-fastapi-app registry.railway.app/${{ secrets.RAILWAY_PROJECT_ID }}/my-fastapi-app:latest
          docker push registry.railway.app/${{ secrets.RAILWAY_PROJECT_ID }}/my-fastapi-app:latest

      - name: Deploy to Railway  # Trigger Railway deployment
        run: curl -X POST -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" https://api.railway.app/projects/${{ secrets.RAILWAY_PROJECT_ID }}/deployments     