name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Railway
        uses: railwayapp/railway-actions@v1
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          
      - name: Wait for deployment
        run: sleep 45  # Increased wait time to ensure deployment is complete
        
      - name: Test API endpoints
        run: |
          echo "Testing FastAPI endpoints on Railway..."
          BASE_URL="${{ secrets.RAILWAY_APP_URL }}"
          
          # Test books list endpoint
          echo "Testing GET /api/v1/books/ endpoint..."
          curl -f "${BASE_URL}/api/v1/books/" || {
            echo "Error: Failed to fetch books list"
            exit 1
          }
          
          # Test single book endpoints
          for book_id in 1 3; do
            echo "Testing GET /api/v1/books/${book_id} endpoint..."
            curl -f "${BASE_URL}/api/v1/books/${book_id}" || {
              echo "Error: Failed to fetch book ${book_id}"
              exit 1
            }
          done
          
          echo "All API endpoint tests completed successfully!"